### ISSUE TITLE
Tracking master

### ISSUE THREAD

**Issue by scarroll32** [bricesanchez/stimulusjs-rails#1]
Great idea, this gem. To use stimulus without webpacker would make life easier for simple Rails applications.

Stimulus is under heavy development, and it might be nice to have a way for this gem to optionally track master.

<img width="890" alt="screen shot 2018-03-23 at 13 08 12" src="https://user-images.githubusercontent.com/11340230/37828381-46be0344-2e9b-11e8-8b6c-2bff44c98769.png">

**Comment by bricesanchez** [comment]
Done https://github.com/bricesanchez/stimulusjs-rails/releases/tag/v.1.0

Thanks !
