### ISSUE TITLE
Suggestion: align versions with Stimulus

### ISSUE THREAD

**Issue by scarroll32** [bricesanchez/stimulusjs-rails#2]
This gem is currently 1.0, tracking Stimulus 1.01. As a suggestion, it might make things clearer if the gem had the same version number as Stimulus.

**Comment by bricesanchez** [comment]
Hi @seanfcarroll, That's a good idea, i will do it at the next release of Stimulus. Thanks!

**Comment by scarroll32** [comment]
Awesome
